default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

test:
  <<: *default
  database: pridepocket_test

development:
  <<: *default
  database: pridepocket_dev

production:
  <<: *default
  database: pridepocket
